// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWei63rqW8EDl4IEXZjzL_QyrzrPi6cLA',
    appId: '1:257554226404:web:7c4b0a6c4d82801f7ba0f1',
    messagingSenderId: '257554226404',
    projectId: 'project-tasky-95425',
    authDomain: 'project-tasky-95425.firebaseapp.com',
    storageBucket: 'project-tasky-95425.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW3oA4TwBU-bJIreGYqoskvseFhwfZH2Q',
    appId: '1:257554226404:android:ae6d0cb2d8a788c07ba0f1',
    messagingSenderId: '257554226404',
    projectId: 'project-tasky-95425',
    storageBucket: 'project-tasky-95425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR4H473EdI3fT15liEhLOgblJGcx-qJl8',
    appId: '1:257554226404:ios:5fd76793a0f3de207ba0f1',
    messagingSenderId: '257554226404',
    projectId: 'project-tasky-95425',
    storageBucket: 'project-tasky-95425.firebasestorage.app',
    iosBundleId: 'com.example.taskyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR4H473EdI3fT15liEhLOgblJGcx-qJl8',
    appId: '1:257554226404:ios:5fd76793a0f3de207ba0f1',
    messagingSenderId: '257554226404',
    projectId: 'project-tasky-95425',
    storageBucket: 'project-tasky-95425.firebasestorage.app',
    iosBundleId: 'com.example.taskyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWei63rqW8EDl4IEXZjzL_QyrzrPi6cLA',
    appId: '1:257554226404:web:89df50a308bce6047ba0f1',
    messagingSenderId: '257554226404',
    projectId: 'project-tasky-95425',
    authDomain: 'project-tasky-95425.firebaseapp.com',
    storageBucket: 'project-tasky-95425.firebasestorage.app',
  );
}
